- debug:
    msg: "Starting setup for {{ lab_id }}..."

- name: Setup user
  user:
    name: "lab{{ lab_id }}"
    generate_ssh_key: yes
  tags:
    - user
    - ssh

- name: Template the terraform.tfvars
  template:
    src: cluster.tfvars.j2
    dest: "/home/lab{{ lab_id }}/cluster.tfvars"

- name: Setup infra
  terraform:
    project_path: kubespray/contrib/terraform/packet
    state: present # Set to absent to `terraform destroy`
    force_init: true
    workspace: "lab{{ lab_id }}" # or state_file
    variables_file: "/home/lab{{ lab_id }}/cluster.tfvars"
  tags:
    - terraform
    - terraform-apply

- name: Install Kubernetes
  # NOTE: Install whole cluter or just master?
  # We could dump the inventory file in the user homedir for them to run Kubespray
  # `--skip-tags download` ?
  command: ansible-playbook -i kubespray/contrib/terraform/packet kubespray/cluster.yml
