- name: Get Kubespray
  git:
    repo: https://github.com/kubernetes-sigs/kubespray.git
    version: "{{ kubespray_version }}"
    dest: /opt/kubespray
  tags:
    - prepare
  run_once: true
  delegate_to: localhost

- name: Install unzip
  package:
    name: unzip
    state: present
  run_once: true
  delegate_to: localhost

- name: Install terraform
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes
  run_once: true
  delegate_to: localhost
