#################################################################################################################
#
# Single t1.small.x86 node
#
# This physical (bare metal) has a single drive so we use storage on the file system
#
# Usage:
#   kubectl create -f cluster-master-only.yaml
#
# For a fully documented reference file, please see:
#   https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml
#
#################################################################################################################

apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v13.2.5-20190410
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  # set the amount of mons to be started
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  storage:
    # only use the single node and devices described
    useAllNodes: false
    useAllDevices: true
# Individual nodes and their config can be specified as well, but 'useAllNodes' above must be set to false. Then, only the named
# nodes below will be used as storage resources.  Each node's 'name' field should match their 'kubernetes.io/hostname' label.
    nodes:
    - name: node1
      directories: # specific directories to use for storage can be specified for each node
      - path: "/var/lib/rook"
