apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-volume
  labels:
    app: example
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
