---
- hosts: localhost
  gather_facts: false
  become: no
  tasks:
    - include_vars: defaults/main.yml
    - include_tasks: tasks/preflight.yml

    - name: Get Kubespray
      git:
        repo: https://github.com/kubernetes-sigs/kubespray.git
        version: "{{ kubespray_version }}"
        # TODO: in /opt ?
        dest: kubespray
      tags:
        - prepare

    - include_tasks: tasks/lab.yml
      loop: "{{ range(0, number_labs) |list }}"
      loop_control:
        loop_var: lab_id
  vars:
    ansible_connection: local
